name: fanex_flutter
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  font_awesome_flutter: ^10.1.0
  webview_flutter: ^3.0.1
  google_fonts: ^2.3.1
  flutter_bloc: ^8.0.1
  flutter_svg: ^1.0.3
  bloc: ^8.0.3
  equatable: ^2.0.3
  getwidget: ^2.0.4
  flutter_swiper: ^1.1.6
  custom_switch: ^0.0.1
  percent_indicator: ^4.0.1
  http: ^0.13.4
  device_info_plus: ^3.2.3
  internet_connection_checker: ^0.0.1+3
  flash: ^2.0.3+1
  cached_network_image: ^3.2.0
  shared_preferences: ^2.0.15



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.2

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/fanex-logo.png"


  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true


  assets:
    - assets/images/
    - assets/icons/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
