name: fanex_flutter
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  google_fonts: ^2.3.1
  getwidget: ^2.0.4
  flutter_swiper: ^1.1.6
  font_awesome_flutter: ^10.1.0
  eva_icons_flutter: ^3.1.0
  flutter_svg: ^1.1.5
  intl: ^0.17.0
  bloc: ^7.0.0
  flutter_bloc: ^7.0.0
  hydrated_bloc: ^7.0.0
  equatable: ^2.0.0
  rxdart: ^0.27.4
  dio: ^4.0.4
  shared_preferences: ^2.0.11
  flutter_secure_storage: ^5.0.2
  http: ^0.13.4
  connectivity_plus: ^2.2.0
  bouncy_container: ^0.0.1
  flutter_dash: ^1.0.0
  webview_flutter: ^2.0.4
  flutter_staggered_grid_view: ^0.6.1
  shimmer: ^2.0.0
  flutter_html: any
  image_picker: ^0.8.4+11
  cached_network_image: ^3.2.0
  #package_info_plus: ^1.4.2
  #device_info_plus: ^8.0.0
  pull_to_refresh: ^2.0.0
  path_provider: ^2.0.7
  readmore: ^2.1.0
  flutter_spinkit: ^5.1.0
  carousel_slider: ^4.1.1
  lottie: ^2.2.0


dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true


  assets:
    - assets/images/
    - assets/icons/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
